import glob
import re

files = glob.glob('templates/*.html')
exclude = ['dashboard.html', 'base.html', 'landing.html', 'login.html']

for filepath in files:
    if any(e in filepath for e in exclude):
        continue
    
    with open(filepath, 'r') as f:
        content = f.read()
    
    # We want to replace huge <p> tags with multiple smaller <p> tags.
    # A simple way is to split by ". " and group them into 2-3 sentences per paragraph.
    def p_replacer(match):
        p_content = match.group(1)
        # Find verses like "Romans 6:4" or "John 3:16" or explicit quotes.
        # Just simple split for now to make it more scannable.
        sentences = p_content.split('. ')
        
        paragraphs = []
        current_p = []
        for s in sentences:
            current_p.append(s)
            if len(current_p) >= 3:
                paragraphs.append('. '.join(current_p) + ('.' if not current_p[-1].endswith('.') else ''))
                current_p = []
        if current_p:
            paragraphs.append('. '.join(current_p) + ('.' if not current_p[-1].endswith('.') else ''))
            
        new_html = ""
        for p in paragraphs:
            # Highlight verses if they exist
            if re.search(r'\b[1-3]?\s?[A-Z][a-z]+\s\d+:\d+\b', p):
                # Has a verse reference
                new_html += f'<div class="p-6 bg-gray-50 dark:bg-white/5 rounded-2xl border-l-4 my-6" style="border-color: currentColor"><p class="text-gray-800 dark:text-gray-200 text-lg font-medium leading-relaxed italic">{p}</p></div>'
            else:
                new_html += f'<p class="text-gray-600 dark:text-gray-400 text-lg leading-relaxed mb-4">{p}</p>'
                
        return new_html

    # We need to only target <p> inside the prose div, or just any <p class="...text-lg leading-relaxed...">
    # Actually, the python regex can just target the exact p tag format generated by the subagents.
    content = re.sub(r'<p class="text-gray-600 dark:text-gray-400 text-lg leading-relaxed(?: mt-4)?">(.*?)</p>', p_replacer, content)
    
    # Also let's make the h3 headers cooler
    content = re.sub(r'<h3 class="text-2xl font-bold mb-4 text-gray-900 dark:text-white">(.*?)</h3>', 
                     r'<h3 class="text-2xl font-bold mb-4 text-gray-900 dark:text-white flex items-center gap-3"><svg class="w-6 h-6 opacity-70" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>\1</h3>', 
                     content)

    with open(filepath, 'w') as f:
        f.write(content)

print("Formatting applied!")
